mysite/config/routes.rb
Mysite::Application.routes.draw do

  resources :projects

  match 'home' => 'home#index', :as => :home
  match 'about' => 'about#index', :as => :about

  root :to => "home#index"

end

mysite/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :content, :description, :github, :title
end

mysite/app/controllers/about_controller.rb
class AboutController < ApplicationController
 
  def index
  end

end

mysite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

mysite/app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def index
  end

end

mysite/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

end

mysite/app/helpers/application_helper.rb
module ApplicationHelper
end

mysite/app/helpers/projects_helper.rb
module ProjectsHelper
end

mysite/app/views/about/index.html.erb
<% @title="About" %>

<h2><%= @title %></h2>

<p>Hi, I'm Richard Race and I'm currently in my final year at Aberystwyth University. I study Software Engineering (MEng).</p>

<p>This site is more based around the work I do rather than my life. So, to give you a little bit of an idea, my main hobby is skiing. But at the moment I can't as I dislocated my shoulder, so I'm concentrating on this site instead!</p>

mysite/app/views/home/index.html.erb
<% @title = "Home" %>
<div class="hero-unit">
	<h2>Hello!</h2>
	<p>This is going to a site that details some of the work I've done. Whether it is a University project, or something I just messed around with.</p>
	<p>Currently, I'm working on this site in my spare time away from Uni work. If you want to look at some of the work I do, check out my GitHub account: <a href="http://github.com/richrace" target="_new">http://github.com/richrace</a></p>
</div>

mysite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
				<a class="brand" href="#">Richard Race's Site</a>
				<div class="nav-collapse collapse">
		            <ul class="nav">		
						<li <%= "class='active'".html_safe if @title.eql?("Home")%>><%= link_to "Home", home_path %></li>
						<li <%= "class='active'".html_safe if @title.eql?("Projects")%>><%= link_to "Projects", projects_path %></li>
						<li <%= "class='active'".html_safe if @title.eql?("About")%>><%= link_to "About", about_path %></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div id="wrap">
  		<div id="main" class="container clear-top">
    		<%= yield %>
  		</div>
	</div>		
	<div class="navbar navbar-fixed-bottom">
		<div class="container">
        	<p>&copy; Richard Race 2013</p>
    	</div>
    </div>
</body>
</html>

mysite/app/views/projects/index.html.erb
<div>
	<% @title="Projects" %>
	<h2><%= @title %></h2>
	<% @projects.each do |project| %>
	  <p>
	    <b><%= project.title %></b>
	    <br />
	    <br />
	    <%= project.description %>
	  </p>
	  <p>
	  	<%= link_to "View Project", project, :class => 'btn' %>
	  	<br />
	    <br />
	  </p>
	<% end %>
</div>

mysite/app/views/projects/show.html.erb
<% @title=@project.title %>

<p><%= link_to '< Back to Projects', projects_path %></b>

<h3><%= @project.title %></h3>
<p>  
  <%= @project.description %>
</p>
<% unless @project.github.nil? %>
<p>
	<%= link_to 'View Source Code on GitHub', @project.github, :target => '_blank' %>
</p>
<% end %>
<p>
  <b>What is it?</b>
  <br />
  <br />
  <%= @project.content %>
</p>